### ISSUE TITLE
search input error

### ISSUE THREAD

**Issue by bo-io-gov-mo** [bo-io-gov-mo/website#71] opened 2016-09-06 02:38 UTC
with quotation mark:
http://betan.io.gov.mo/pt/search/?o=0&tab=&s=0&q=%22fernando%22

**Comment by xiquinho** [comment] 2016-09-06 03:00
same before

**Comment by bo-io-gov-mo** [comment] 2016-09-06 03:03
opposite of before. cn no error, pt have error.

**Comment by xiquinho** [comment] 2016-09-06 04:16
fixed for both. on the left up screen you will see the input string after cleaning, is for debug  only

**Comment by bo-io-gov-mo** [comment] 2016-09-06 04:21
Did you remove the quotation mark? quotation mark means match phase exactly.
below cases should be not same:
http://betan.io.gov.mo/pt/search/?o=0&tab=&s=0&q=%22chan+chi+sang%22
http://betan.io.gov.mo/pt/search/?o=0&tab=&s=0&q=chan+chi+sang

**Comment by xiquinho** [comment] 2016-09-06 04:31
I don't think you can  search for match phase exactly using CONTAINSTABLE. Either I remove it or return an error:

http://betan.io.gov.mo/pt/search/?o=0&tab=&s=0&q=%22chan+chi+sang%22

**Comment by bo-io-gov-mo** [comment] 2016-09-06 04:47
sql  [CONTAINS ](https://msdn.microsoft.com/en-us/library/ms187787.aspx) can search for: a word or phrase.
````
<simple_term> ::=   { word | "phrase" }
````
in chinese search no error:
http://betan.io.gov.mo/cn/search/?o=0&tab=&s=0&q=%22chan+chi+sang%22
http://betan.io.gov.mo/cn/search/?o=0&tab=&s=0&q=chan+chi+sang

**Comment by xiquinho** [comment] 2016-09-06 04:54
Yes, you are right, my mistake, let me fix it. Only Portuguese, the Chinese is ok, your script handle it, am I  correct?

**Comment by bo-io-gov-mo** [comment] 2016-09-06 05:10
It is handle by your ParseUserInput function. I think the gammer chinese and portuguese are different. 
In chinese. 
1. When type:  **boy girl**  usually means **boy + girl**.
2. When type:  **boyGirl** usually same as above. (here is most different from english need to word break)
3. When type **"boy girl"** usually means **boy** be close to **girl** like phrase.

**Comment by xiquinho** [comment] 2016-09-06 06:35
ParseUserInput  only handles option 1 in PT, because in the old search the other options were handled in other functions. What I want to know is if you want I handle this in CN or not?

**Comment by bo-io-gov-mo** [comment] 2016-09-06 06:40
I tested CN is fine now. you want need more handle of chinese?

**Comment by bo-io-gov-mo** [comment] 2016-09-08 01:10
I think chinese these issue happen on pt, doesn't change it on cn.

**Comment by xiquinho** [comment] 2016-09-08 02:07
I don't fix yet planning for today.

**Comment by xiquinho** [comment] 2016-09-08 09:21
this is now fixed and the other tabs are ready for test except the sort (can test, but I'm not sure is ready yet) , pl, let me know if you find any mistake

**Comment by xiquinho** [comment] 2016-09-12 01:17
I found some bugs on PT version during the weekend, pl hold on any further testing on PT until I fixed it. Only affects PT.

**Comment by bo-io-gov-mo** [comment] 2016-09-12 01:18
noted.

**Comment by xiquinho** [comment] 2016-09-12 04:46
query to reproduce on SMS:

declare @0 nvarchar(256) = 'FORMSOF(INFLECTIONAL, decreto-lei) AND FORMSOF(INFLECTIONAL, 87) AND FORMSOF(INFLECTIONAL, 89) AND FORMSOF(INFLECTIONAL, m) '

--declare @0 nvarchar(256) = '"decreto-lei" AND "87" AND "89" AND "m" '


;With result_set As (Select ROW_NUMBER() OVER ( ORDER BY (Case When KEY_TBL.title_Rank > 0 Then KEY_TBL.title_Rank+FT_TBL.Visits_cn*100 Else KEY_TBL.title_Rank End) DESC, (Case When KEY_TBL.text_Rank > 0 Then KEY_TBL.text_Rank+FT_TBL.Visits_cn*100 Else KEY_TBL.text_Rank End) DESC, DatePublished DESC ) AS [row_number], FT_TBL.DiplomNamept AS DipName, FT_TBL.DiplomDescpt AS DipDesc, FT_TBL.LinkID, FT_TBL.DatePublished, FT_TBL.DiplomUrl, FT_TBL.BONumber, FT_TBL.BOYear, FT_TBL.Serie, FT_TBL.pagina, FT_TBL.suplemento, 'a' as Tab , KEY_TBL.Title_RANK as [RANK] FROM tbo2004 As FT_TBL INNER JOIN ( SELECT SUM(t.Title_Rank) AS Title_RANK, SUM(t.text_Rank) AS Text_RANK, s.tboID, s.LinkID, s.tab FROM ( SELECT [KEY], Rank as Title_Rank, 0 AS Text_Rank FROM CONTAINSTABLE(search, title_pt, @0,language 2070) UNION ALL SELECT [KEY], 0 AS Title_Rank, Rank as Text_rank FROM CONTAINSTABLE(search, text_pt, @0,language 2070) ) as T INNER JOIN Search as S on T.[key]=S.tboID GROUP BY S.tboID, S.LinkID, S.tab ) AS KEY_TBL ON (FT_TBL.LinkID=KEY_TBL.LinkID and KEY_TBL.tab='a') WHERE FT_TBL.Active = 'True' AND FT_TBL.DipDisplay = 1 ) Select * FROM result_set WHERE [row_number] BETWEEN 0 And 240

**Comment by bo-io-gov-mo** [comment] 2016-09-12 05:52
I got the problem in search table, I will fix it asap.

**Comment by xiquinho** [comment] 2016-09-12 06:18
I don’t think the problem is on the search table, the problem is on the query. I test the old query on the search table and it is ok. I think the problem is on the Ranks and the on Unions ALL, ie, how the query is constructed, but I can’t help as I don’t have any idea about what are you trying to do with this algorithm of yours...

**Comment by xiquinho** [comment] 2016-09-12 08:21
another example (have many more like this..)

When the PT users search for 
**arrendamento** 

they are looking for this:
Código Civil - Art. 1001 a 1100, Código Civil - Art. 1001 a 1100 
http://betapt.io.gov.mo/BO/A/Link/17221.aspx

In the old search this result cames on 4th place (is not perfect, but is there)

Now in the new search where it is? Nowhere?

**Comment by bo-io-gov-mo** [comment] 2016-09-12 08:55
1. **89/87/M** and relate fixed: http://betan.io.gov.mo/pt/search/?o=0&tab=a&s=0&q=87%2F89%2FM&n=&y= , it is better now?


2. **arrendamento** is correct, new search show title have keyword first priority than text. This is more make sense than title and text same weight. Because sql server fts no field weight to adjust for search rank priority. 
Old search is not good because, for example: if one record text refer the origin record many times(always happen on law's characteristic), default fts query always cannot show origin.

**Comment by xiquinho** [comment] 2016-09-13 01:24
This is more make sense for you and you only, because you don’t understand that when you search for arrendamento it was the result above that should came first, no matter what you say about the fields weight or the goodness of old search. But since you say it is correct, I am not going to insist, I just hope when someone will complain you don’t say this is my idea or my work and I will have problems with this, that’s my only concern.

**Comment by bo-io-gov-mo** [comment] 2016-09-13 01:53
You don't know how many complain of existing search year by year ago. I know the problem and situation, but FTS how can do what powerful feature!? whatever 'arrendamento' or others synonymity, how can you control the rank!? If we still argument in ms-fts that is totally no meaning, it is a blem search engine.  Now I only want to enhance base on existing architecture intent to make more sense what before not: **what user type correct term can output result to them**, synonymity or intelligent is still missing. 

Something you are right, this new search distance to GOOD is so much far. It is a small step to gain time to replace a search engine. That's why I always speak to you about solr or google or something like this. If you have time later, welcome to found a good solution. It is always open.

**Comment by xiquinho** [comment] 2016-09-13 02:25
You told me before the problem was in the Chinese word breaker. Never, but never, ever once, you discuss anything with me about any problem in the rank and for me this is just another surprise. And while I agree your idea is good with some queries, for others clearly is not. 

I just show you an example where the new search completely fails, but you insist it is correct, what more can I say, what more solutions can I found? I suggest the google, long time ago, you refused it, I suggest the zoom search engine, which I get very good results in the last edition of cd-rom, you refused it. And now you are “improving” the search engine but where are the improvements? And it’s not only PT this happens. Try search for arrendamento (一般規定) in chinese and you have the same "improvement". The part in civil code related to  arrendamento (一般規定) vanished from the results. But my intention was only to warn you about this problem, if you feel this is the correct solution, go ahead and forget what I said.

**Comment by bo-io-gov-mo** [comment] 2016-09-13 05:32
Ok, for case discussion:
1. keyword:一般規定 is word break to 一般~規定, if you search quotation mark with "一般規定" is similar with existing, but this meaning is generic, I think word break is more suitable (if not want to word break need add this term into dictionary, we need continuous update Chinese dict soon).

2. keyword: arrendamento, I already explain because title first priority rule.

I know search is a fuzzy and big data engineering, discuss the logic and rule are better then by case, especially on ms-FTS limitation feature(better these will make bad those), but if you found some typical case, I will try to adjust it. pls feel free to tell me your warning.

**Comment by xiquinho** [comment] 2016-09-13 07:07
As I said before, I just wanted to let you know about this problem, some records should appears on the search results and they are not there. And if you are getting better results in some cases, I am  also getting worst results in another cases, I just want let you know about it, not argue about what is better or not. But if you think this is correct, forget what I said, it doesn’t matter discuss more about it, we both know you are always correct and everything you do now is much better than what I did before.

**Comment by bo-io-gov-mo** [comment] 2016-09-13 09:11
Your finding is a good case. I want you know we need continuous to update the chinese dictionary for term of chinese word. It is hard to do, because sometime word break is fine and sometime not. Anyway, I want you know we can adjust rank order by diplomlvl or dictionary(cn) further that before cannot. It is a prejudice to sort title first, I know not everything better than before. Finally I want you know this new search also not the best expectation search engine.

**Closed** 2016-09-14 03:37 UTC
